"""Add election id to the Denials

Revision ID: 1012be96aad7
Revises: 60949f4a5f66
Create Date: 2018-10-16 23:56:31.775437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1012be96aad7'
down_revision = '60949f4a5f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denial', sa.Column('electionId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('denial', 'electionId')
    # ### end Alembic commands ###
