"""denials

Revision ID: 60949f4a5f66
Revises: 5b875533b995
Create Date: 2018-10-14 19:53:59.040400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60949f4a5f66'
down_revision = '5b875533b995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optPersonName', sa.String(length=140), nullable=True),
    sa.Column('optPersonStreet', sa.String(length=140), nullable=True),
    sa.Column('optPersonCity', sa.String(length=140), nullable=True),
    sa.Column('optPersonState', sa.String(length=2), nullable=True),
    sa.Column('optPersonZip', sa.String(length=10), nullable=True),
    sa.Column('optEmail', sa.String(length=120), nullable=True),
    sa.Column('pollZip', sa.String(length=10), nullable=True),
    sa.Column('pollStreet', sa.String(length=140), nullable=True),
    sa.Column('pollCity', sa.String(length=140), nullable=True),
    sa.Column('pollState', sa.String(length=2), nullable=True),
    sa.Column('pollName', sa.String(length=50), nullable=True),
    sa.Column('poc', sa.Boolean(), nullable=True),
    sa.Column('registration_type', sa.String(length=1), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denial_timestamp'), 'denial', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_denial_timestamp'), table_name='denial')
    op.drop_table('denial')
    # ### end Alembic commands ###
